server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-gestion-usuarios-service
          uri: lb://ms-gestion-usuarios-service
          predicates:
            - Path=/usuarios/**