server:
  port: 8084
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pedidos
    username: root
    password:


eureka:
  process:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
  instance:
    hostname: localhost